apiVersion: v1
kind: Service
metadata:
  name: users-loadbalancer
  namespace: assignment3
  labels:
    app: users-service
spec:
  type: LoadBalancer
  ports:
    - port: 5050 
      targetPort: 5501
  selector:
    app: users
