apiVersion: v1
kind: Service
metadata:
  name: users-nodeport
  namespace: assignment3
  labels:
    app: users-service
spec:
  type: NodePort
  ports:
    - port: 5050 
      targetPort: 5501
      nodePort: 6000
  selector:
    app: users
