apiVersion: v1
kind: Service
metadata:
  name: shortener-loadbalancer
  namespace: assignment3
  labels:
    app: shortener-service
spec:
  type: LoadBalancer
  ports:
    - port: 5051
      targetPort: 5500
  selector:
    app: shortener
