apiVersion: v1
kind: Service
metadata:
  name: proxy-loadbalancer
  namespace: assignment3
  labels:
    app: proxy-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: proxy
