apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: assignment3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy-container
          imagePullPolicy: Always
          image: index.docker.io/abhilashbalaji/wscbsa3:proxy
          ports:
            - containerPort: 80

